apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozilla-tts-deployment
  labels:
    app: mozilla-tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mozilla-tts
  template:
    metadata:
      labels:
        app: mozilla-tts
    spec:
      containers:
      - name: mozilla-tts
        image: synesthesiam/mozillatts:en
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: mozilla-tts-service
  labels:
    app: mozilla-tts
  annotations:
    dev.okteto.com/auto-ingress: "true"  
spec:
  type: LoadBalancer
  selector:
    app: mozilla-tts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5002
